import { useEffect, useState } from 'react';
import { api } from '../api.js';
import { Alert, Pill, when } from '../ui.jsx';
import VisitNoteForm from './VisitNoteForm.jsx';

function PreVisit({ appointmentId }) {
  const [s, setS] = useState(undefined);
  const load = () =>
    api(`/api/appointments/${appointmentId}/pre-visit-summary`).then(setS).catch(() => setS(null));
  useEffect(() => { load(); }, [appointmentId]);

  if (s === undefined) return <p className="muted">Loading…</p>;
  if (!s) return <p className="muted">No symptom form was submitted.</p>;

  return (
    <div style={{ marginTop: 10 }}>
      {s.status === 'READY' ? (
        <>
          <div className="row">
            <h3 style={{ margin: 0 }}>AI pre-visit summary</h3>
            <Pill>{s.urgencyLevel}</Pill>
          </div>
          <p>{s.chiefComplaint}</p>
          <h3>Suggested questions</h3>
          <ul className="tight">{s.suggestedQuestions.map((q, i) => <li key={i}>{q}</li>)}</ul>
          <p className="muted">
            Generated by {s.model} ({s.promptVersion}). Decision support only — not a diagnosis.
          </p>
        </>
      ) : (
        <div className="alert error" style={{ background: '#fffbeb', color: '#b45309', borderColor: '#f0dcb4' }}>
          {s.status === 'FAILED'
            ? 'The AI summary could not be generated. The patient’s own words are below.'
            : 'The AI summary is still being prepared. The patient’s own words are below.'}
          {s.status === 'FAILED' && (
            <button
              className="ghost"
              style={{ marginLeft: 10 }}
              onClick={() =>
                api(`/api/appointments/${appointmentId}/pre-visit-summary/regenerate`, {
                  method: 'POST', body: { force: true },
                }).then(load)
              }
            >
              Retry
            </button>
          )}
        </div>
      )}

      {/* Raw symptoms are always shown, so a model outage never leaves the
          doctor with nothing to read. */}
      {s.symptomReport && (
        <>
          <h3 style={{ marginTop: 12 }}>Reported by the patient</h3>
          <p>{s.symptomReport.symptomsText}</p>
          <p className="muted">
            {s.symptomReport.durationDays != null && `Duration: ${s.symptomReport.durationDays} day(s). `}
            {s.symptomReport.severity != null && `Severity: ${s.symptomReport.severity}/10. `}
            {s.symptomReport.currentMedications && `Medications: ${s.symptomReport.currentMedications}.`}
          </p>
        </>
      )}
    </div>
  );
}

export default function DoctorAppointments() {
  const [items, setItems] = useState([]);
  const [error, setError] = useState('');
  const [open, setOpen] = useState(null);
  const [noting, setNoting] = useState(null);

  const load = () =>
    api('/api/appointments?limit=50')
      .then((r) => setItems(r.data))
      .catch((e) => setError(e.message));

  useEffect(() => { load(); }, []);

  if (noting) {
    return (
      <VisitNoteForm
        appointment={noting}
        onCancel={() => setNoting(null)}
        onDone={() => { setNoting(null); load(); }}
      />
    );
  }

  return (
    <>
      <h1>My schedule</h1>
      <Alert>{error}</Alert>
      {items.length === 0 && <p className="muted">No appointments.</p>}

      {items.map((a) => (
        <div key={a.id} className="card">
          <div className="row">
            <strong>{a.patient?.fullName}</strong>
            <Pill>{a.status}</Pill>
            <span className="right muted">{when(a.slotStart)}</span>
          </div>

          <div className="row" style={{ marginTop: 10 }}>
            <button className="ghost" onClick={() => setOpen(open === a.id ? null : a.id)}>
              {open === a.id ? 'Hide details' : 'View symptoms'}
            </button>
            {a.status === 'CONFIRMED' && (
              <button onClick={() => setNoting(a)}>Complete visit</button>
            )}
          </div>

          {open === a.id && <PreVisit appointmentId={a.id} />}
        </div>
      ))}
    </>
  );
}
