import dotenv from 'dotenv';
import { z } from 'zod';

dotenv.config();

// Fail fast and loudly at boot rather than at the first request that needs a
// missing variable. Anything with a sane default gets one so `cp .env.example
// .env` is enough to start in development.
const bool = (def) =>
  z
    .string()
    .optional()
    .transform((v) => (v === undefined ? def : v.toLowerCase() === 'true'));

const int = (def) =>
  z
    .string()
    .optional()
    .transform((v) => (v === undefined ? def : Number.parseInt(v, 10)))
    .pipe(z.number().int());

const schema = z.object({
  NODE_ENV: z.enum(['development', 'test', 'production']).default('development'),
  PORT: int(4000),
  API_BASE_URL: z.string().url().default('http://localhost:4000'),
  CLIENT_BASE_URL: z.string().url().default('http://localhost:5173'),
  CLINIC_TIMEZONE: z.string().default('Asia/Kolkata'),

  DATABASE_URL: z.string().min(1, 'DATABASE_URL is required'),

  JWT_ACCESS_SECRET: z.string().min(16, 'JWT_ACCESS_SECRET must be at least 16 chars'),
  JWT_REFRESH_SECRET: z.string().min(16, 'JWT_REFRESH_SECRET must be at least 16 chars'),
  JWT_ACCESS_TTL: z.string().default('15m'),
  JWT_REFRESH_TTL: z.string().default('7d'),
  BCRYPT_ROUNDS: int(10),
  TOKEN_ENCRYPTION_KEY: z
    .string()
    .regex(/^[0-9a-fA-F]{64}$/, 'TOKEN_ENCRYPTION_KEY must be 64 hex chars (32 bytes)'),

  SLOT_HOLD_TTL_SECONDS: int(600),
  APPOINTMENT_REMINDER_LEAD_MINUTES: int(1440),

  LLM_PROVIDER: z.enum(['groq', 'gemini', 'openrouter', 'mock']).default('mock'),
  LLM_TIMEOUT_MS: int(20000),
  LLM_MAX_ATTEMPTS: int(3),
  GROQ_API_KEY: z.string().optional().default(''),
  GROQ_MODEL: z.string().default('llama-3.3-70b-versatile'),
  GEMINI_API_KEY: z.string().optional().default(''),
  GEMINI_MODEL: z.string().default('gemini-2.0-flash'),
  OPENROUTER_API_KEY: z.string().optional().default(''),
  OPENROUTER_MODEL: z.string().default('meta-llama/llama-3.3-70b-instruct:free'),

  MAIL_TRANSPORT: z.enum(['console', 'smtp']).default('console'),
  SMTP_HOST: z.string().optional().default(''),
  SMTP_PORT: int(587),
  SMTP_SECURE: bool(false),
  SMTP_USER: z.string().optional().default(''),
  SMTP_PASS: z.string().optional().default(''),
  MAIL_FROM_NAME: z.string().default('Clinic Care'),
  MAIL_FROM_EMAIL: z.string().default('no-reply@clinic.example'),

  GOOGLE_CLIENT_ID: z.string().optional().default(''),
  GOOGLE_CLIENT_SECRET: z.string().optional().default(''),
  GOOGLE_REDIRECT_URI: z.string().default('http://localhost:4000/api/calendar/google/callback'),
  GOOGLE_CALENDAR_ENABLED: bool(false),

  WORKER_ENABLED: bool(true),
  WORKER_POLL_INTERVAL_MS: int(15000),
  WORKER_BATCH_SIZE: int(20),
});

const parsed = schema.safeParse(process.env);

if (!parsed.success) {
  const issues = parsed.error.issues
    .map((i) => `  - ${i.path.join('.')}: ${i.message}`)
    .join('\n');
  console.error(`\nInvalid environment configuration:\n${issues}\n`);
  console.error('Copy server/.env.example to server/.env and fill in the values.\n');
  process.exit(1);
}

export const env = parsed.data;

export const isProd = env.NODE_ENV === 'production';
export const isDev = env.NODE_ENV === 'development';
export const isTest = env.NODE_ENV === 'test';

// A provider is only considered usable if its key is actually present. This is
// what lets the LLM layer fall back to a degraded-but-working mode instead of
// throwing at boot.
export function activeLlmProvider() {
  const keyFor = {
    groq: env.GROQ_API_KEY,
    gemini: env.GEMINI_API_KEY,
    openrouter: env.OPENROUTER_API_KEY,
    mock: 'n/a',
  };
  const chosen = env.LLM_PROVIDER;
  if (chosen !== 'mock' && !keyFor[chosen]) {
    console.warn(
      `[llm] LLM_PROVIDER="${chosen}" but no API key is set - falling back to "mock". ` +
        'Summaries will be generated by a deterministic stub.'
    );
    return 'mock';
  }
  return chosen;
}
